#!/bin/bash
# 功能：
# 	1.把当天必应的壁纸下载到指定目录，并设置为壁纸
# history:
#	1.基本功能完成
#	2.2017年04月09日18:32:45
#		修改图片名称为当前时间戳
#	3.2017年04月11日19:39:58
#   	重构

# 必应网址
baseUrl="http://cn.bing.com"

#保存图片的image_url
image_url=""
localPath="/home/kegao/Pictures/Wallpapers/"
#图片的绝对路径
picture="${localPath}$(date '+%s').jpg"

#获取必应壁纸的url
function getUrl(){
	# curl -sS $baseUrl 爬取必应的source
	# | 管道符 前面的输出 为后面的输入
	# grep -o 使用正则表达式查找匹配到的字符串
	image_url=$(curl -sS $baseUrl | grep -o "g_img={url:[^,]*") # 2017年04月11日19:53:12 输入结果为 g_img={url: "/az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg"
	
	#删除冒号前面的部分 ## 从前面开始删除字符串
	image_url=${image_url##*:} # g_img={url: "/az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg"  -> "/az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg"

	#删除掉冒号  // 替换命令，把冒号替换为空，即是删除冒号
	image_url=${image_url//\"} # "/az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg" -> /az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg
	#同上 删除 空格
	image_url=${image_url//\ } 

	#拼接成完整url 
	image_url=${baseUrl}${image_url} # http://cn.bing.com/az/hprichbg/rb/WindmillLighthouse_ZH-CN12870536851_1920x1080.jpg
}

#下载壁纸
function downloadImg(){
	# wget 下载 
	# &> 不显示其他信息
	wget $image_url -O ${picture} &>/dev/null
}

#设置刚才下载下来的为壁纸 只是用与 gonme桌面
function setAsBackground(){
	gsettings set org.gnome.desktop.background picture-uri "file:${picture}"
}


#执行刚才的fuction
mkdir -p ${localPath}
getUrl
downloadImg
setAsBackground
